import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MainNav } from "@/components/main-nav";
import { ColorModeToggle } from "@/components/color-mode-toggle";
import { ThemeProvider } from "next-themes";
import { Analytics } from "@vercel/analytics/next";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import Link from "next/link";
import { config } from "@/config";
import { Icons } from "@/components/icons";
import { Button, buttonVariants } from "@/components/ui/button";
import { GitHubLogoIcon } from "@radix-ui/react-icons";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function NavItem({
  tooltip,
  href,
  children,
}: {
  tooltip: string;
  href: string;
  children: React.ReactElement;
}) {
  return (
    <Tooltip delayDuration={0}>
      <TooltipTrigger asChild>
        <Link href={href} className={cn(buttonVariants({ variant: "ghost" }))}>
          {children}
        </Link>
      </TooltipTrigger>
      <TooltipContent
        side="bottom"
        className="rounded border bg-background text-foreground"
      >
        <span className="text-xs">{tooltip}</span>
      </TooltipContent>
    </Tooltip>
  );
}

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-6`}
      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="dark">
          <TooltipProvider>
            <div className="p-8 space-y-4">
              <header className="max-w-xl m-auto mb-4">
                <div className="flex items-center justify-between">
                  <MainNav />
                  <div className="flex flex-1 items-center justify-end space-x-2">
                    <nav className="flex items-center space-x-1">
                      <NavItem tooltip="github" href={config.socials.bsky}>
                        <>
                          <GitHubLogoIcon className="text-foreground h-5 w-5" />
                          <span className="sr-only">GitHub</span>
                        </>
                      </NavItem>
                    </nav>
                    <ColorModeToggle />
                  </div>
                </div>
              </header>
              {children}
            </div>
          </TooltipProvider>
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
