import { ColorModeToggle } from "@/components/color-mode-toggle";
import { MainNav } from "@/components/main-nav";
import { TooltipProvider } from "@/components/ui/tooltip";
import { config } from "@/config";
import { Analytics } from "@vercel/analytics/next";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="dark">
          <TooltipProvider>
            <div className="space-y-4 max-w-xl mx-auto flex flex-col h-full min-h-screen p-4 md:py-8">
              <header className="mb-4">
                <div className="flex items-center justify-between">
                  <MainNav />
                  <div className="flex flex-1 items-center justify-end space-x-2">
                    <nav className="flex items-center space-x-4">
                      <Link
                        className="no-underline"
                        href={config.socials.github}
                      >
                        GitHub
                      </Link>
                      <Link
                        className="no-underline"
                        href={config.socials.github}
                      >
                        Bluesky
                      </Link>
                    </nav>
                    <ColorModeToggle />
                  </div>
                </div>
              </header>
              {children}
              <div className="items-end flex-1 flex flex-col justify-end">
                <span>2025</span>
              </div>
            </div>
          </TooltipProvider>
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
